mws/mws/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
import apimws.views
import apimws.bes
import apimws.lv
import mwsauth.views
import sitesmanagement.views
from sitesmanagement.views.domains import DomainListView, DomainDelete
from sitesmanagement.views.sites import SiteCreate, SiteShow, SiteList, SiteDisable, SiteDelete, SiteEdit, \
    SiteEditEmail, SiteDoNotRenew
from sitesmanagement.views.snapshots import SnapshotCreate, SnapshotDelete, SnapshotListView
from sitesmanagement.views.unixgroups import UnixGroupListView, UnixGroupCreate, UnixGroupDelete, UnixGroupUpdate
from sitesmanagement.views.vhosts import VhostListView, VhostDelete, VhostCreate

urlpatterns = [
    # external apps urls
    url(r'', include('ucamwebauth.urls')),

    # admin app urls
    url(r'^admin/', include(admin.site.urls)),

    # lookup/ibis urls
    url(r'^ucamlookup/', include('ucamlookup.urls')),

    # Site management
    url(r'^$', SiteList.as_view(), name='listsites'),
    url(r'^site/new/$', SiteCreate.as_view(), name='newsite'),
    url(r'^site/show/(?P<site_id>[0-9]+)/$', SiteShow.as_view(), name='showsite'),
    url(r'^site/edit/(?P<site_id>[0-9]+)/$', SiteEdit.as_view(), name='editsite'),
    url(r'^site/email/(?P<site_id>[0-9]+)/$', SiteEditEmail.as_view(), name='editsitemail'),
    url(r'^site/delete/(?P<site_id>[0-9]+)/$', SiteDelete.as_view(), name='deletesite'),
    url(r'^site/disable/(?P<site_id>[0-9]+)/$', SiteDisable.as_view(), name='disablesite'),
    url(r'^site/donotrenew/(?P<site_id>[0-9]+)/$', SiteDoNotRenew.as_view(), name='donotrenew'),

    # Service management
    url(r'^status/(?P<service_id>[0-9]+)/$', sitesmanagement.views.service_status, name='sitesmanagement.views.service_status'),
    url(r'^settings/(?P<service_id>[0-9]+)/$', sitesmanagement.views.service_settings, name='sitesmanagement.views.service_settings'),
    url(r'^billing/(?P<site_id>[0-9]+)/$', sitesmanagement.views.billing_management, name='billing_management'),
    url(r'^enable/(?P<site_id>[0-9]+)/$', sitesmanagement.views.sites.site_enable, name='enablesite'),
    url(r'^unsuspend/(?P<site_id>[0-9]+)/$', sitesmanagement.views.sites.site_unsuspend, name='unsuspendsite'),
    url(r'^vhosts/(?P<vhost_id>[0-9]+)/certificates/$', sitesmanagement.views.certificates, name='sitesmanagement.views.certificates'),
    url(r'^vhosts/(?P<vhost_id>[0-9]+)/generate_csr/$', sitesmanagement.views.generate_csr, name='sitesmanagement.views.generate_csr'),
    url(r'^delete_vm/(?P<service_id>[0-9]+)/$', sitesmanagement.views.delete_vm, name='sitesmanagement.views.delete_vm'),
    url(r'^settings/vm/(?P<service_id>[0-9]+)/on/$', sitesmanagement.views.power_vm, name='sitesmanagement.views.power_vm'),
    url(r'^settings/vm/(?P<service_id>[0-9]+)/reset/$', sitesmanagement.views.reset_vm, name='sitesmanagement.views.reset_vm'),
    url(r'^settings/vm/(?P<service_id>[0-9]+)/db_root_pass/$', sitesmanagement.views.change_db_root_password, name='change_db_root_password'),
    # url(r'^apache/(?P<service_id>[0-9]+)/$', sitesmanagement.views.apache_modules, name='sitesmanagement.views.apache_modules'),
    url(r'^phplibs/(?P<service_id>[0-9]+)/$', sitesmanagement.views.php_libs, name='sitesmanagement.views.php_libs'),
    url(r'^quarantine/(?P<service_id>[0-9]+)/$', sitesmanagement.views.quarantine, name='sitesmanagement.views.quarantine'),

    # Vhosts management
    url(r'^vhosts/(?P<service_id>[0-9]+)/$', VhostListView.as_view(), name='listvhost'),
    url(r'^add_vhost/(?P<service_id>[0-9]+)/$', VhostCreate.as_view(), name='createvhost'),
    url(r'^vhosts/(?P<vhost_id>[0-9]+)/delete/$', VhostDelete.as_view(), name='deletevhost'),
    url(r'^vhost/(?P<vhost_id>[0-9]+)/apache_owned$', sitesmanagement.views.vhost_onwership, name='vhostapache'),

    # Domains management
    url(r'^add_domain/(?P<vhost_id>[0-9]+)/$', sitesmanagement.views.add_domain, name='sitesmanagement.views.add_domain'),
    url(r'^set_dn_as_main/(?P<domain_id>[0-9]+)/$', sitesmanagement.views.set_dn_as_main, name='sitesmanagement.views.set_dn_as_main'),
    url(r'^domains/(?P<vhost_id>[0-9]+)/$', DomainListView.as_view(), name='listdomains'),
    url(r'^delete_domain/(?P<domain_id>[0-9]+)/$', DomainDelete.as_view(), name='deletedomain'),

    # Unix groups management
    url(r'^unix_groups/(?P<service_id>[0-9]+)/$', UnixGroupListView.as_view(), name='listunixgroups'),
    url(r'^unix_groups/(?P<service_id>[0-9]+)/add/$', UnixGroupCreate.as_view(), name='createunixgroup'),
    url(r'^unix_groups/edit/(?P<ug_id>[0-9]+)/$', UnixGroupUpdate.as_view(), name='updateunixgroup'),
    url(r'^unix_groups/delete/(?P<ug_id>[0-9]+)/$', UnixGroupDelete.as_view(), name='deleteunixgroup'),

    # Snapshot management
    url(r'^create_snapshot/(?P<service_id>[0-9]+)/$', SnapshotCreate.as_view(), name='createsnapshot'),
    url(r'^delete_snapshot/(?P<snapshot_id>[0-9]+)/$', SnapshotDelete.as_view(), name='deletesnapshot'),
    url(r'^backups/(?P<service_id>[0-9]+)/$', SnapshotListView.as_view(), name='backups'),

    # bes++ api
    url(r'^bes/$', apimws.bes.bes, name='apimws.bes.bes'),

    # update snapshots
    url(r'^update_lv_list/$', apimws.lv.update_lv_list, name='apimws.lv.update_lv_list'),

    # apimws app
    url(r'^api/confirm_dns/(?P<dn_id>[0-9]+)/(?P<token>.+)/$', apimws.views.confirm_dns, name='apimws.views.confirm_dns'),
    url(r'^api/finance/billing/$', apimws.views.billing_total, name='apimws.views.billing_total'),
    url(r'^api/finance/billing/(?P<year>20[0-9]{2})/(?P<month>[0-9]{1,2})/$', apimws.views.billing_month, name='apimws.views.billing_month'),
    url(r'^confirm_email/(?P<ec_id>[0-9]+)/(?P<token>(\w|\-)+)/$', apimws.views.confirm_email, name='apimws.views.confirm_email'),
    url(r'^api/post_installation/$', apimws.views.post_installation, name='apimws.views.post_installation'),
    url(r'^api/post_recreate/$', apimws.views.post_recreate, name='apimws.views.post_recreate'),
    url(r'^api/resend_email_confirmation/(?P<site_id>[0-9]+)/$', apimws.views.resend_email_confirmation_view, name='apimws.views.resend_email_confirmation_view'),

    # test os updates
    url(r'^clone_vm/(?P<site_id>[0-9]+)/$', sitesmanagement.views.clone_vm_view, name='sitesmanagement.views.clone_vm_view'),
    url(r'^switch_services/(?P<site_id>[0-9]+)/$', sitesmanagement.views.switch_services, name='sitesmanagement.views.switch_services'),

    # mwsauth app
    url(r'^auth/(?P<site_id>[0-9]+)/$', mwsauth.views.auth_change, name='mwsauth.views.auth_change'),
    url(r'^auth/(?P<site_id>[0-9]+)/force_update/$', mwsauth.views.force_update, name='mwsauth.views.force_update'),
    url(r'^auth/(?P<site_id>[0-9]+)/add_supporter/$', mwsauth.views.add_supporter, name='mwsauth.views.add_supporter'),

    # user panel
    url(r'^user_panel/$', mwsauth.views.user_panel, name='mwsauth.views.user_panel'),

    # file serve for purchase order files
    url(r'^media/billing/(?P<filename>[^/]+)$', sitesmanagement.views.po_file_serve, name='sitesmanagement.views.po_file_serve'),

    # Global
    url(r'^privacy/$', sitesmanagement.views.privacy, name='sitesmanagement.views.privacy'),
    url(r'^termsandconditions/$', sitesmanagement.views.termsconds, name='sitesmanagement.views.termsconds'),

    # Admin
    url(r'^searchadmin/$', sitesmanagement.views.admin_search, name='searchadmin'),
    url(r'^adminemailist/$', sitesmanagement.views.others.admin_email_list, name='adminemailist'),

    # Stats
    url(r'^stats/$', apimws.views.stats, name='stats'),
    url(r'^stats/datainuse$', apimws.views.statsdatainuse, name='apimws.views.statsdatainuse'),
    url(r'^stats/datarequests$', apimws.views.statsdatarequests, name='apimws.views.statsdatarequests'),
    url(r'^stats/dataactive$', apimws.views.statsdataactive, name='apimws.views.statsdataactive'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mws/sitesmanagement/models.py
import uuid
import re
import reversion
from datetime import datetime, timedelta, date
from itertools import chain
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import validate_slug
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.db import transaction
from django.utils import timezone
from django.utils.timezone import now
from os.path import splitext
from ucamlookup.models import LookupGroup
from apimws.ipreg import DomainNameDelegatedException
from mwsauth.utils import get_users_of_a_group
from sitesmanagement.utils import get_object_or_None, deprecated


class NetworkConfig(models.Model):
    NETWORK_CONFIGURATION_TYPES = (
        ('ipv4pub', 'Public IPv4 Only'),
        ('ipv4priv', 'Private IPv4 Only'),
        ('ipvxpub', 'Public IPv4 and IPv6'),
        ('ipvxpriv', 'Private IPv4 and IPv6'),
        ('ipv6', 'IPv6 Only'),
    )

    IPv4 = models.GenericIPAddressField(protocol='IPv4', unique=True, null=True, blank=True)
    IPv4_netmask = models.GenericIPAddressField(protocol='IPv4', null=True, blank=True)
    IPv4_gateway = models.GenericIPAddressField(protocol='IPv4', null=True, blank=True)
    IPv6 = models.GenericIPAddressField(protocol='IPv6', unique=True, null=True, blank=True)
    name = models.CharField(max_length=250, unique=True)
    type = models.CharField(max_length=50, choices=NETWORK_CONFIGURATION_TYPES)

    @classmethod
    def get_free_prod_service_config(cls):
        return cls.objects.filter(service=None, type='ipvxpub').first()

    @classmethod
    def get_free_test_service_config(cls):
        return cls.objects.filter(service=None, type='ipv4priv').first()

    @classmethod
    def get_free_host_config(cls):
        return cls.objects.filter(vm=None, type='ipv6').first()

    def __unicode__(self):
        return self.name


class ServerType(models.Model):
    numcpu = models.IntegerField()
    sizeram = models.IntegerField()  # In GB
    sizedisk = models.IntegerField()  # In GB
    preallocated = models.IntegerField()  # Number of pre-allocated server of this type
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.CharField(max_length=100, blank=True, null=True)
    order = models.IntegerField()

    def __unicode__(self):
        return self.description or "%d CPU cores, %dGB of RAM, %dGB of SSD Disk, %s pounds per year" % \
                                   (self.numcpu, self.sizeram, self.sizedisk-5, self.price)


class Site(models.Model):
    """
    The site which is purchased by a user. It is the primary object which a
    user interacts with.

    :py:class:`.Site` object have the following fields:

    preallocated
        Is this a "preallocated" site as described in :any:`vmlifecycle`.
    name
        Human-friendly name of the site
    description
        Human-friendly description of the site
    institution_id
        The owning institution (retrieved using lookup)
    start_date
        Start date of the site
    end_date
        End date of the site (when the site will be cancelled, scheduled by the user or other reasons)
    deleted
        Is the site deleted?
    email
        Webmaster email
    subscription
        Indicates if the user wants to renew or their MWS3 subscription
    type
        Server type (amount of CPU, RAM, and disk)
    users
        Administrator users of a site
    ssh_users
        SSH only users of a site
    groups
        A set of :py:class:`.LookupGroup` instances representing the
        administrator groups of a site.
    ssh_groups
        SSH only groups
    supporters
        Supporters list (list of MWS support admins temporary added to the user list)
    disabled
        Indicates if the site is disabled by the user
    days_without_admin
        Number of days since the site lost its last admin
    exmws2
        Flag to mark Grandfathered MWS2 sites (Real date of start)

    """
    preallocated = models.BooleanField(default=False)
    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=250, blank=True)
    institution_id = models.CharField(max_length=100, blank=True, null=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    deleted = models.BooleanField(default=False)
    email = models.EmailField(null=False, blank=False)
    subscription = models.BooleanField(default=True)

    type = models.ForeignKey(ServerType)

    users = models.ManyToManyField(User, related_name='sites')
    ssh_users = models.ManyToManyField(User, related_name='sites_auth_as_user', blank=True)
    groups = models.ManyToManyField(LookupGroup, related_name='sites', blank=True)
    ssh_groups = models.ManyToManyField(LookupGroup, related_name='sites_auth_as_user', blank=True)
    supporters = models.ManyToManyField(User, related_name='sites_auth_as_supporter', blank=True)

    disabled = models.BooleanField(default=False)

    days_without_admin = models.IntegerField(default=0)

    exmws2 = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ["-id"]
    #
    # def clean(self):
    #     # Don't allow empty start_date for a non preallocated site (already on production)
    #     if not self.preallocated and self.start_date is None:
    #         raise ValidationError('start date cannot be null if the site is not a preallocated one')

    def get_absolute_url(self):
        """Return an absolute URL for this site's control panel."""
        from django.core.urlresolvers import reverse
        return reverse('showsite', args=[str(self.id)])

    def __unicode__(self):
        return self.name

    # @property
    # def virtual_machines(self):
    #     return VirtualMachine.objects.filter(service__site_id=self.id)

    def is_admin_suspended(self):
        for susp in self.suspensions.all():
            if susp.active:
                return True
        return False

    def is_canceled(self):
        return self.end_date is not None

    def is_disabled(self):
        return self.disabled

    def suspend_now(self, input_reason):
        return Suspension.objects.create(reason=input_reason, start_date=datetime.today(), site=self)

    def unsuspend(self):
        suspensions = Suspension.objects.filter(site=self)
        for susp in suspensions:
            if susp.active:
                susp.end_date = now()
                susp.save()
        return True

    @property
    def vms(self):
        return VirtualMachine.objects.filter(service__site=self)

    @property
    def production_vms(self):
        return self.vms.filter(service__type='production')

    @property
    def test_vms(self):
        return self.vms.filter(service__type='test')

    @property
    def production_service(self):
        return Service.objects.filter(type='production', site=self).first()

    @property
    def test_service(self):
        return Service.objects.filter(type='test', site=self).first()

    @property
    @deprecated
    def primary_vm(self):
        return self.vms.filter(service__type='production').first()

    @property
    @deprecated
    def secondary_vm(self):
        return self.vms.filter(service__type='test').first()

    @property
    def domain_names(self):
        return DomainName.objects.filter(vhost__service=self.production_service)

    def cancel(self):
        self.end_date = datetime.today()
        self.users.clear()
        self.ssh_users.clear()
        self.groups.clear()
        self.ssh_groups.clear()
        self.save()
        if self.production_service:
            self.production_service.power_off()
        if self.test_service:
            self.test_service.power_off()

    def disable(self):
        if self.disabled:
            return False
        self.disabled = True
        self.save()
        if self.production_service:
            self.production_service.power_off()
        if self.test_service:
            self.test_service.power_off()
        return True

    def enable(self):
        if not self.disabled:
            return False
        self.disabled = False
        self.save()
        if self.production_service:
            self.production_service.power_on()
        if self.test_service:
            self.test_service.power_on()
        return True

    def switch_services(self):
        prod_service = self.production_service
        test_service = self.test_service
        netconf_prod = prod_service.network_configuration
        netconf_test = test_service.network_configuration
        vhost_prod = prod_service.vhosts.all()
        ug_prod = prod_service.unix_groups.all()

        with transaction.atomic():
            # Switch vhosts, test service has no vhosts
            for vhost in vhost_prod:
                vhost.service = test_service
                vhost.save()

            # Switch unix groups, test service has no UG
            for ug in ug_prod:
                ug.service = test_service
                ug.save()

            # Switch network configuration
            test_service.network_configuration = NetworkConfig.get_free_test_service_config()
            test_service.type = "production"
            test_service.site = None
            test_service.save()
            prod_service.network_configuration = netconf_test
            prod_service.type = "test"
            prod_service.save()
            test_service.site = self
            test_service.network_configuration = netconf_prod
            test_service.save()

            from apimws.models import AnsibleConfiguration
            AnsibleConfiguration.objects.update_or_create(service=test_service, key="backup_first_date",
                                                          value=date.today().isoformat())

        from apimws.ansible import launch_ansible

mws/templates/mws/admin/email_list.html
{% extends 'project-light/campl-mws.html' %}
{% block page_content %}
    {{ block.super }}
    <div class="campl-column12 campl-main-content">
        <div class="campl-content-container">
            <h1>Admin email list</h1>
            <div><p>
            {% for site in site_list %}
                {{ site.email }}<br/>
            {% endfor %}
            </p></div>
        </div>
    </div>
{% endblock %}

mws/templates/mws/admin/search.html
{% extends 'project-light/campl-mws.html' %}
{% block page_content %}
    {{ block.super }}
    <div class="campl-column12 campl-main-content">
        <div class="campl-content-container">
            <h1>Search MWS servers</h1>
            {% if results %}
                <table class="campl-table-bordered campl-table-striped campl-table campl-vertical-stacking-table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Hostnames</th>
                            <th>Server info</th>
                            <th>Admin Users</th>
                            <th>SSH Users</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for site in results %}
                            <tr data-href="{% url 'showsite' site_id=site.id %}">
                                <td>
                                    {{ site.name }}<br/>
                                    {% if site.is_canceled %}<br/>This site is cancelled{% endif %}
                                    {% if site.is_disabled %}
                                        <br/>This site is disabled<br/>
                                        <form action={% url 'enablesite' site_id=site.id %} method="post">
                                            <fieldset>
                                                {% csrf_token %}
                                                <input type="submit" value="Re-enable" class="campl-btn campl-primary-cta">
                                            </fieldset>
                                        </form>
                                    {% endif %}
                                    {% if site.is_admin_suspended %}
                                        <br/>This site is administrativelly suspended<br/>
                                        <form action={% url 'unsuspendsite' site_id=site.id %} method="post">
                                            <fieldset>
                                                {% csrf_token %}
                                                <input type="submit" value="Unsuspend" class="campl-btn campl-primary-cta">
                                            </fieldset>
                                        </form>
                                    {% endif %}
                                </td>
                                <td>
                                    {{ site.description }}
                                </td>
                                <td>
                                    {{ site.domain_names|join:"<br/>" }}
                                </td>
                                <td>
                                    {{ site.type.description }}
                                    {% if site.production_service %}
                                        IPv4: {{ site.production_service.ipv4 }}<br/>
                                        IPv6: {{ site.production_service.ipv6 }}<br/>
                                        servicename: {{ site.production_service.hostname }}<br/>
                                        hostname: {{ site.production_vms.0.hostname }}<br/>
                                    {% endif %}
                                </td>
                                <td>
                                    {% for user in site.list_of_admins %}
                                        {{ user.last_name }} ({{ user.username }})<br/>
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for user in site.list_of_ssh_users %}
                                        {{ user.last_name }} ({{ user.username }})<br/>
                                    {% endfor %}
                                </td>
                                <td style="width: 30px; padding-left: 0px; padding-right: 0px;">
                                    <a href="{% url 'showsite' site_id=site.id %}">
                                        <i title="Control panel" class="fa fa-angle-double-right fa-2x"
                                           data-toggle="tooltip"></i>
                                    </a>
                                </td>
                            </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
            <form action="{% url 'searchadmin' %}" method="post">
                <fieldset>
                    {% csrf_token %}
                    <div id="site_form">
                        <p>
                            <label for="id_mwsname">MWS Name</label>
                            <input id="id_mwsname" maxlength="100" name="mwsname" type="text">
                        </p>
                        <p>
                            <label for="id_mwshostname">MWS Server Name</label>
                            <input id="id_mwshostname" maxlength="200" name="mwshostname" type="text">
                        </p>
                        <p>
                            <label for="id_mwsdomainname">MWS Hostname</label>
                            <input id="id_mwsdomainname" maxlength="200" name="mwsdomainname" type="text">
                        </p>
                        <p>
                            <label for="id_crsid">MWS User</label>
                            <input id="id_crsid" maxlength="100" name="crsid" type="text">
                        </p>
                    </div>
                    <p><input type="submit" value="Search" class="campl-btn campl-primary-cta"></p>
                </fieldset>
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block campl_foot_js %}
    {% include 'ucamlookup_users.html' with input_tag_id="id_crsid" multiple="false" %}
{% endblock %}