mws/mws/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
import apimws.views
import apimws.bes
import apimws.lv
import mwsauth.views
import sitesmanagement.views
from sitesmanagement.views.domains import DomainListView, DomainDelete
from sitesmanagement.views.sites import SiteCreate, SiteShow, SiteList, SiteDisable, SiteDelete, SiteEdit, \
    SiteEditEmail, SiteDoNotRenew
from sitesmanagement.views.snapshots import SnapshotCreate, SnapshotDelete, SnapshotListView
from sitesmanagement.views.unixgroups import UnixGroupListView, UnixGroupCreate, UnixGroupDelete, UnixGroupUpdate
from sitesmanagement.views.vhosts import VhostListView, VhostDelete, VhostCreate

urlpatterns = [
    # external apps urls
    url(r'', include('ucamwebauth.urls')),

    # admin app urls
    url(r'^admin/', include(admin.site.urls)),

    # lookup/ibis urls
    url(r'^ucamlookup/', include('ucamlookup.urls')),

    # Site management
    url(r'^$', SiteList.as_view(), name='listsites'),
    url(r'^site/new/$', SiteCreate.as_view(), name='newsite'),
    url(r'^site/show/(?P<site_id>[0-9]+)/$', SiteShow.as_view(), name='showsite'),
    url(r'^site/edit/(?P<site_id>[0-9]+)/$', SiteEdit.as_view(), name='editsite'),
    url(r'^site/email/(?P<site_id>[0-9]+)/$', SiteEditEmail.as_view(), name='editsitemail'),
    url(r'^site/delete/(?P<site_id>[0-9]+)/$', SiteDelete.as_view(), name='deletesite'),
    url(r'^site/disable/(?P<site_id>[0-9]+)/$', SiteDisable.as_view(), name='disablesite'),
    url(r'^site/donotrenew/(?P<site_id>[0-9]+)/$', SiteDoNotRenew.as_view(), name='donotrenew'),

    # Service management
    url(r'^status/(?P<service_id>[0-9]+)/$', sitesmanagement.views.service_status, name='sitesmanagement.views.service_status'),
    url(r'^settings/(?P<service_id>[0-9]+)/$', sitesmanagement.views.service_settings, name='sitesmanagement.views.service_settings'),
    url(r'^billing/(?P<site_id>[0-9]+)/$', sitesmanagement.views.billing_management, name='billing_management'),
    url(r'^enable/(?P<site_id>[0-9]+)/$', sitesmanagement.views.sites.site_enable, name='enablesite'),
    url(r'^unsuspend/(?P<site_id>[0-9]+)/$', sitesmanagement.views.sites.site_unsuspend, name='unsuspendsite'),
    url(r'^vhosts/(?P<vhost_id>[0-9]+)/certificates/$', sitesmanagement.views.certificates, name='sitesmanagement.views.certificates'),
    url(r'^vhosts/(?P<vhost_id>[0-9]+)/generate_csr/$', sitesmanagement.views.generate_csr, name='sitesmanagement.views.generate_csr'),
    url(r'^delete_vm/(?P<service_id>[0-9]+)/$', sitesmanagement.views.delete_vm, name='sitesmanagement.views.delete_vm'),
    url(r'^settings/vm/(?P<service_id>[0-9]+)/on/$', sitesmanagement.views.power_vm, name='sitesmanagement.views.power_vm'),
    url(r'^settings/vm/(?P<service_id>[0-9]+)/reset/$', sitesmanagement.views.reset_vm, name='sitesmanagement.views.reset_vm'),
    url(r'^settings/vm/(?P<service_id>[0-9]+)/db_root_pass/$', sitesmanagement.views.change_db_root_password, name='change_db_root_password'),
    # url(r'^apache/(?P<service_id>[0-9]+)/$', sitesmanagement.views.apache_modules, name='sitesmanagement.views.apache_modules'),
    url(r'^phplibs/(?P<service_id>[0-9]+)/$', sitesmanagement.views.php_libs, name='sitesmanagement.views.php_libs'),
    url(r'^quarantine/(?P<service_id>[0-9]+)/$', sitesmanagement.views.quarantine, name='sitesmanagement.views.quarantine'),

    # Vhosts management
    url(r'^vhosts/(?P<service_id>[0-9]+)/$', VhostListView.as_view(), name='listvhost'),
    url(r'^add_vhost/(?P<service_id>[0-9]+)/$', VhostCreate.as_view(), name='createvhost'),
    url(r'^vhosts/(?P<vhost_id>[0-9]+)/delete/$', VhostDelete.as_view(), name='deletevhost'),
    url(r'^vhost/(?P<vhost_id>[0-9]+)/apache_owned$', sitesmanagement.views.vhost_onwership, name='vhostapache'),

    # Domains management
    url(r'^add_domain/(?P<vhost_id>[0-9]+)/$', sitesmanagement.views.add_domain, name='sitesmanagement.views.add_domain'),
    url(r'^set_dn_as_main/(?P<domain_id>[0-9]+)/$', sitesmanagement.views.set_dn_as_main, name='sitesmanagement.views.set_dn_as_main'),
    url(r'^domains/(?P<vhost_id>[0-9]+)/$', DomainListView.as_view(), name='listdomains'),
    url(r'^delete_domain/(?P<domain_id>[0-9]+)/$', DomainDelete.as_view(), name='deletedomain'),

    # Unix groups management
    url(r'^unix_groups/(?P<service_id>[0-9]+)/$', UnixGroupListView.as_view(), name='listunixgroups'),
    url(r'^unix_groups/(?P<service_id>[0-9]+)/add/$', UnixGroupCreate.as_view(), name='createunixgroup'),
    url(r'^unix_groups/edit/(?P<ug_id>[0-9]+)/$', UnixGroupUpdate.as_view(), name='updateunixgroup'),
    url(r'^unix_groups/delete/(?P<ug_id>[0-9]+)/$', UnixGroupDelete.as_view(), name='deleteunixgroup'),

    # Snapshot management
    url(r'^create_snapshot/(?P<service_id>[0-9]+)/$', SnapshotCreate.as_view(), name='createsnapshot'),
    url(r'^delete_snapshot/(?P<snapshot_id>[0-9]+)/$', SnapshotDelete.as_view(), name='deletesnapshot'),
    url(r'^backups/(?P<service_id>[0-9]+)/$', SnapshotListView.as_view(), name='backups'),

    # bes++ api
    url(r'^bes/$', apimws.bes.bes, name='apimws.bes.bes'),

    # update snapshots
    url(r'^update_lv_list/$', apimws.lv.update_lv_list, name='apimws.lv.update_lv_list'),

    # apimws app
    url(r'^api/confirm_dns/(?P<dn_id>[0-9]+)/(?P<token>.+)/$', apimws.views.confirm_dns, name='apimws.views.confirm_dns'),
    url(r'^api/finance/billing/$', apimws.views.billing_total, name='apimws.views.billing_total'),
    url(r'^api/finance/billing/(?P<year>20[0-9]{2})/(?P<month>[0-9]{1,2})/$', apimws.views.billing_month, name='apimws.views.billing_month'),
    url(r'^confirm_email/(?P<ec_id>[0-9]+)/(?P<token>(\w|\-)+)/$', apimws.views.confirm_email, name='apimws.views.confirm_email'),
    url(r'^api/post_installation/$', apimws.views.post_installation, name='apimws.views.post_installation'),
    url(r'^api/post_recreate/$', apimws.views.post_recreate, name='apimws.views.post_recreate'),
    url(r'^api/resend_email_confirmation/(?P<site_id>[0-9]+)/$', apimws.views.resend_email_confirmation_view, name='apimws.views.resend_email_confirmation_view'),

    # test os updates
    url(r'^clone_vm/(?P<site_id>[0-9]+)/$', sitesmanagement.views.clone_vm_view, name='sitesmanagement.views.clone_vm_view'),
    url(r'^switch_services/(?P<site_id>[0-9]+)/$', sitesmanagement.views.switch_services, name='sitesmanagement.views.switch_services'),

    # mwsauth app
    url(r'^auth/(?P<site_id>[0-9]+)/$', mwsauth.views.auth_change, name='mwsauth.views.auth_change'),
    url(r'^auth/(?P<site_id>[0-9]+)/force_update/$', mwsauth.views.force_update, name='mwsauth.views.force_update'),
    url(r'^auth/(?P<site_id>[0-9]+)/add_supporter/$', mwsauth.views.add_supporter, name='mwsauth.views.add_supporter'),

    # user panel
    url(r'^user_panel/$', mwsauth.views.user_panel, name='mwsauth.views.user_panel'),

    # file serve for purchase order files
    url(r'^media/billing/(?P<filename>[^/]+)$', sitesmanagement.views.po_file_serve, name='sitesmanagement.views.po_file_serve'),

    # Global
    url(r'^privacy/$', sitesmanagement.views.privacy, name='sitesmanagement.views.privacy'),
    url(r'^termsandconditions/$', sitesmanagement.views.termsconds, name='sitesmanagement.views.termsconds'),

    # Admin
    url(r'^searchadmin/$', sitesmanagement.views.admin_search, name='searchadmin'),
    url(r'^adminemailist/$', sitesmanagement.views.others.admin_email_list, name='adminemailist'),

    # Stats
    url(r'^stats/$', apimws.views.stats, name='stats'),
    url(r'^stats/datainuse$', apimws.views.statsdatainuse, name='apimws.views.statsdatainuse'),
    url(r'^stats/datarequests$', apimws.views.statsdatarequests, name='apimws.views.statsdatarequests'),
    url(r'^stats/dataactive$', apimws.views.statsdataactive, name='apimws.views.statsdataactive'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mws/apimws/forms.py
from django import forms
from apimws.models import PHPLib
# from apimws.models import ApacheModule
#
#
# class ApacheModuleForm(forms.Form):
#     apache_modules = forms.MultipleChoiceField(
#         choices=tuple(ApacheModule.objects.filter(available=True).values_list('name','description')),
#         label='', widget=forms.CheckboxSelectMultiple(), required=False)


class PHPLibForm(forms.Form):
    php_libs = forms.MultipleChoiceField(
        choices=tuple((phplib.name, phplib.name + " - " + phplib.description)
                      for phplib in PHPLib.objects.filter(available=True).order_by('name')),
        label='', widget=forms.SelectMultiple(), required=False)

mws/sitesmanagement/views/domains.py
"""Views(Controllers) for managing Domain Names"""
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseForbidden, HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, DeleteView
from apimws.ansible import launch_ansible
from apimws.ipreg import set_cname
from apimws.utils import ip_register_api_request
from mwsauth.utils import privileges_check
from sitesmanagement.forms import DomainNameFormNew
from sitesmanagement.models import Vhost, DomainName
from sitesmanagement.utils import is_camacuk, is_camacuk_subdomain
from sitesmanagement.views.vhosts import VhostPriviledgeCheck


class DomainPriviledgeCheck(VhostPriviledgeCheck):
    def dispatch(self, request, *args, **kwargs):
        domain = get_object_or_404(DomainName, pk=self.kwargs['domain_id'])
        self.domain = domain
        self.kwargs['vhost_id'] = domain.vhost.id
        return super(DomainPriviledgeCheck, self).dispatch(request, *args, **kwargs)


class DomainListView(VhostPriviledgeCheck, ListView):
    """View(Controller) to show the list of domains names associated a the selected vhost. The template/view associated
     allows the user to add or delete domain names and to select a domain name as the main domain name for the vhost"""
    model = Vhost
    template_name = 'mws/domains.html'

    def get_context_data(self, **kwargs):
        context = super(DomainListView, self).get_context_data(**kwargs)
        breadcrumbs = {
            0: dict(name='Managed Web Service server: ' + str(self.site.name), url=self.site.get_absolute_url()),
            1: dict(name='Server settings' if self.vhost.service.primary else 'Test server settings',
                    url=reverse('sitesmanagement.views.service_settings',
                                kwargs={'service_id': self.vhost.service.id})),
            2: dict(name='Web sites management: %s' % self.vhost.name,
                    url=reverse('listvhost', kwargs={'service_id': self.vhost.service.id})),
            3: dict(name='Domain Names management',
                    url=reverse('listdomains', kwargs={'vhost_id': self.vhost.id}))
        }
        context.update({
            'breadcrumbs': breadcrumbs,
            'vhost': self.vhost,
            'site': self.site,
            'service': self.vhost.service,
            'domains': self.vhost.domain_names.all(),
            'ndomains': self.vhost.domain_names.count(),
            'domain_form': DomainNameFormNew()
        })
        return context

    def get_queryset(self):
        return self.vhost.domain_names


@login_required
def add_domain(request, vhost_id, socket_error=None):
    """View(Controller) to add a domain name to the vhost selected. """
    vhost = get_object_or_404(Vhost, pk=vhost_id)
    site = privileges_check(vhost.service.site.id, request.user)
    service = vhost.service

    if site is None:
        return HttpResponseForbidden()

    if not service or not service.active or service.is_busy:
        return redirect(site)

    if request.method == 'POST':
        domain_form = DomainNameFormNew(request.POST)
        if domain_form.is_valid():
            domain_requested = domain_form.save(commit=False)
            if domain_requested.name != '':
                if is_camacuk(domain_requested.name):
                    if domain_requested.name.endswith(".usertest.mws3.csx.cam.ac.uk"):
                        new_domain = DomainName.objects.create(name=domain_requested.name, status='accepted',
                                                               vhost=vhost, requested_by=request.user)
                        new_domain.accept_it()
                    elif domain_requested.name.endswith(".mws3.csx.cam.ac.uk"):
                        new_domain = DomainName.objects.create(name=domain_requested.name, status='denied',
                                                               vhost=vhost, requested_by=request.user)
                    elif 'special_case' in domain_form.data:
                        new_domain = DomainName.objects.create(name=domain_requested.name, status='special',
                                                               vhost=vhost, requested_by=request.user,
                                                               reject_reason="User marked as special")
                    else:
                        new_domain = DomainName.objects.create(name=domain_requested.name, status='requested',
                                                               vhost=vhost, requested_by=request.user)
                        ip_register_api_request.delay(new_domain)
                else:
                    new_domain = DomainName.objects.create(name=domain_requested.name, status='external', vhost=vhost,
                                                           requested_by=request.user)
                    if vhost.main_domain is None or \
                                    vhost.main_domain.name == vhost.service.network_configuration.name:
                        vhost.main_domain = new_domain
                        vhost.save()
                launch_ansible(vhost.service)  # to add the new domain name to the vhost apache configuration
        else:
            breadcrumbs = {
                0: dict(name='Managed Web Service server: ' + str(site.name), url=site.get_absolute_url()),
                1: dict(name='Server settings' if vhost.service.primary else 'Test server settings',
                        url=reverse('sitesmanagement.views.service_settings',
                                    kwargs={'service_id': vhost.service.id})),
                2: dict(name='Web sites management: %s' % vhost.name,
                        url=reverse('listvhost',
                                    kwargs={'service_id': vhost.service.id})),
                3: dict(name='Domain Names management', url=reverse('listdomains', kwargs={'vhost_id': vhost.id}))
            }

            return render(request, 'mws/domains.html', {
                'breadcrumbs': breadcrumbs,
                'vhost': vhost,
                'site': site,
                'service': vhost.service,
                'domain_form': domain_form,
                'error': True
            })

    return redirect(reverse('listdomains', kwargs={'vhost_id': vhost.id}))


@login_required
def set_dn_as_main(request, domain_id):
    """View(Controller) to set the domain name selected as the main domain of the vhost"""
    domain = get_object_or_404(DomainName, pk=domain_id)
    vhost = domain.vhost
    site = privileges_check(vhost.service.site.id, request.user)
    service = vhost.service

    if site is None:
        return HttpResponseForbidden()

    if not service or not service.active or service.is_busy:
        return redirect(site)

    if request.method == 'POST':
        vhost.main_domain = domain
        vhost.save()
        launch_ansible(vhost.service)  # to update the vhost main domain name in the apache configuration

    return HttpResponseRedirect(reverse('listdomains', kwargs={'vhost_id': vhost.id}))


class DomainDelete(DomainPriviledgeCheck, DeleteView):
    """View to delete the domain name selected."""
    model = DomainName
    pk_url_kwarg = 'domain_id'

    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse('listdomains', kwargs={'vhost_id': self.vhost.id}))

    def delete(self, request, *args, **kwargs):
        if self.domain.name != self.domain.vhost.service.network_configuration.name:
            if self.domain != self.domain.vhost.main_domain or self.domain.vhost.domain_names.count() == 1:
                self.domain.delete()
                launch_ansible(self.service)
                return HttpResponse()
        return HttpResponseForbidden()

    def get_success_url(self):
        return reverse('listdomains', kwargs={'vhost_id': self.vhost.id})

mws/templates/mws/add_unix_group.html
{% extends 'project-light/campl-mws.html' %}
{% load static %}
{% block page_content %}
    {{ block.super }}
    <div class="campl-column12 campl-main-content">
        <div class="campl-content-container">
            <h1>Add a Unix Group to your "{{ service.site.name }}" {% if service.primary %}production{% else %}test{% endif %} server</h1>
            <p>Unix Group names can only contain letters and need to be written in capital letters</p>
            <form action={% url 'createunixgroup' service_id=service.id %} method="post">
                <fieldset>
                    {% csrf_token %}
                    <div id="unix_group_form">
                        {{ form.as_p }}
                        <p>
                            Users:<br/>
                            <input id="input-lookup-users-ajax" name="unix_users">
                        </p>
                    </div>
                    <p><input type="submit" value="Submit" class="campl-btn campl-primary-cta"/></p>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}

{% block campl_foot_js %}
    {% include 'ucamlookup_users.html' with input_tag_id="input-lookup-users-ajax" multiple="true" user_list="unix_users" %}
{% endblock %}

mws/templates/mws/apache.html
{% extends 'project-light/campl-mws.html' %}
{% load static %}

{% block app_head %}
    {{ block.super }}
    <link href="{% static 'stylesheets/bootstrap-switch.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap-switch.min.js' %}"></script>
{% endblock %}

{% block page_content %}
    {{ block.super }}
    <div class="campl-column12 campl-main-content">
        <div class="campl-content-container">
            <h2>Apache Modules</h2>
            <p>You can enable or disable the following Apache modules:</p>
            <form action="{% url 'sitesmanagement.views.apache_modules' service_id=service.id %}" method="post">
                {% if error_message %}<p style="color: red">{{ error_message }}</p>{% endif %}
                <fieldset>
                    {% csrf_token %}
                    <div>
                        {{ form.as_p }}
                    </div>
                    <p><input type="submit" value="Submit" class="campl-btn campl-primary-cta"/></p>
                </fieldset>
            </form>
            <p>The following Apache modules installed and enabled by 
            default:</p>
            <p>core_module,
               so_module,
               watchdog_module,
               http_module,
               log_config_module,
               logio_module,
               version_module,
               unixd_module,
               access_compat_module,
               actions_module,
               alias_module,
               asis_module,
               auth_basic_module,
               authn_core_module,
               authn_file_module,
               authz_core_module,
               authz_groupfile_module,
               authz_host_module,
               authz_user_module,
               autoindex_module,
               deflate_module,
               dir_module,
               env_module,
               expires_module,
               filter_module,
               headers_module,
               include_module,
               ldap_module,
               mime_module,
               mpm_prefork_module,
               negotiation_module,
               php5_module,
               remoteip_module,
               rewrite_module,
               setenvif_module,
               socache_shmcb_module,
               speling_module,
               ssl_module,
               status_module,
               ucam_webauth_module,
               wsgi_module</p>
        </div>
    </div>
{% endblock %}

{% block campl_foot_js %}
    <script>
        $.fn.bootstrapSwitch.defaults.size = 'mini';
        $(document).ready(function() {
            $("[name='apache_modules']").bootstrapSwitch();
        });
    </script>
{% endblock %}

mws/templates/mws/auth.html
{% extends 'project-light/campl-mws.html' %}
{% block page_content %}
    {{ block.super }}
    <div class="campl-column12 campl-main-content">
        <div class="campl-content-container">
            <h1>Authorised users and groups</h1>

            <p>You can authorise other users as administrators or ssh-only users. Administrators will have access to all
                the features of the control panel and can connect to the server via SSH. SSH-only users will only have
                access to the server via SSH. They won't be able to access the web panel.</p>
            <p>You can search for other users using the text field below by typing their name or CRSid. It will let you
                autocomplete by selecting their entry from the drop-down list.</p>
            <p>You can also authorise users or administrators using
                <a href="http://www.ucs.cam.ac.uk/lookup/">Lookup</a>
                <a href="http://www.ucs.cam.ac.uk/lookup/groups">groups</a>.
            </p>

            <form action={% url 'mwsauth.views.auth_change' site_id=site.id %} method="post" style="float: left; width: 65%;">
                <fieldset>
                    {% csrf_token %}
                    <p>
                        Administrators:<br/>
                        <input id="input-lookup-users-ajax" name="users_crsids">
                    </p>
                    <p>
                        SSH-only users:<br/>
                        <input id="input-lookup-sshusers-ajax" name="sshusers_crsids">
                    </p>
                    <p>
                        Administrators lookup groups:<br/>
                        <input id="input-lookup-groups-ajax" name="groupids">
                    </p>
                    <p>
                        SSH-only lookup groups:<br/>
                        <input id="input-lookup-sshgroups-ajax" name="sshgroupids">
                    </p>
                    <p><input type="submit" value="Submit" class="campl-btn campl-primary-cta"/></p>
                </fieldset>
            </form>
            <div style="background-color: #999999; float: left; width: 25%; padding: 20px 5% 10px 5%;">
                <p>The list of users authorised using Lookup groups are refreshed every 24 hours. If you want to refresh
                it now, you can use the following button.</p>
                <form action={% url 'mwsauth.views.force_update' site_id=site.id %} method="post">
                    <fieldset>
                        {% csrf_token %}
                        <p><input type="submit" value="Force update" class="campl-btn campl-primary-cta"/></p>
                    </fieldset>
                </form>
            </div>
            {% if request.user.is_superuser %}
            <div style="float: left; width: 31%; padding: 15px 2% 10px 2%;">
                <p>This is the current list of supporters for this MWS server: {{ site.supporters.all|join:',' }}</p>
                <p>If you want to add yourself as a supporter click the button below. After 1 hour you will be
                    deleted from the supporter list</p>
                <form action={% url 'mwsauth.views.add_supporter' site_id=site.id %} method="post">
                    <fieldset>
                        {% csrf_token %}
                        <p><input type="submit" value="Add yourself" class="campl-btn campl-primary-cta"></p>
                    </fieldset>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block campl_foot_js %}
    {% include 'ucamlookup_users.html' with input_tag_id="input-lookup-users-ajax" multiple="true" user_list="authorised_users" %}
    {% include 'ucamlookup_users.html' with input_tag_id="input-lookup-sshusers-ajax" multiple="true" user_list="sshuserlist" %}
    {% include 'ucamlookup_groups.html' with input_tag_id="input-lookup-groups-ajax" multiple="true" group_list="authorised_groups" %}
    {% include 'ucamlookup_groups.html' with input_tag_id="input-lookup-sshgroups-ajax" multiple="true" group_list="sshusers_groups" %}
{% endblock %}

mws/templates/mws/certificates.html
{% extends 'project-light/campl-mws.html' %}
{% load static %}
{% block page_content %}
    {{ block.super }}
    <div class="campl-column12 campl-main-content">
        <div class="campl-content-container">
            <h1>TLS/SSL certificate for the Web site "{{ vhost.name }}"</h1>
            {% if error_main_domain %}
                <div class="campl-notifications-panel campl-warning-panel campl-notifications-container clearfix">
					<div class="campl-column4">
						<p class="campl-notifications-icon campl-warning-icon">Warning:</p>
					</div>
					<div class="campl-column8">
						<p>A CSR couldn't be generated because you don't have a master hostname assigned to this vhost.</p>
					</div>
                </div>
            {% endif %}
            {% if vhost.tls_key_hash != 'requested' and vhost.tls_key_hash != 'renewal' and vhost.tls_key_hash != 'renewal_cert' %}
                <form action="{% url 'sitesmanagement.views.generate_csr' vhost_id=vhost.id %}" method="post">
                    <fieldset>
                        {% csrf_token %}
                        <p><input type="submit" value="Generate {% if vhost.csr or vhost.certificate %} a new {% endif %}TLS Certificate request (CSR)" class="campl-btn campl-primary-cta campl-primary-blue"/></p>
                    </fieldset>
                </form>
                    {% if vhost.certificate %}
                        <h3>{% if vhost.tls_key_hash == 'renewal_waiting_cert' %}Current {% endif %}TLS certificate</h3>
                        <pre>{{ vhost.certificate }}</pre>
                    {% endif %}
            {% elif vhost.tls_key_hash == 'renewal_cert' %}
                <p>The new certificate is being installed</p>
            {% else %}
                <p>The {% if vhost.certificate %} a new {% endif %} TLS certificate request (CSR) is being generated</p>
            {% endif %}
            {% if vhost.csr and not vhost.certificate or vhost.tls_key_hash == 'renewal_waiting_cert' %}
                <h3>{% if vhost.tls_key_hash == 'renewal_waiting_cert' %}Renewal (new) {% endif %}TLS Certificate Request (CSR)</h3>
                <pre>{{ vhost.csr }}</pre>
                <form id="key_cert_form" enctype="multipart/form-data" action="{% url 'sitesmanagement.views.certificates' vhost_id=vhost.id %}" method="post">
                    {% if error_message %}<p style="color: red">Error: {{ error_message }}</p>{% endif %}
                    <fieldset>
                        {% csrf_token %}
                        <p {% if not vhost.csr %}style="display: none;"{% endif %}>
                            {% if vhost.tls_key_hash == 'renewal_waiting_cert' %}Upload renewal (new) {% endif %}Certificate file: <input type="file" name="cert"></p>
                        <p {% if not vhost.csr %}style="display: none;"{% endif %}>
                            <input type="submit" value="Submit" class="campl-btn campl-primary-cta"/></p>
                    </fieldset>
                </form>
            {% endif %}

        </div>
    </div>
{% endblock %}

mws/templates/mws/phplibs.html
{% extends 'project-light/campl-mws.html' %}
{% load static %}

{% block app_head %}
    {{ block.super }}
    <style>
        .select2-selection__choice {
            float: none !important;
        }

        .select2-container {
            width: 75% !important;
            max-width: 800px !important;
        }
    </style>
{% endblock %}

{% block page_content %}
    {{ block.super }}
    <div class="campl-column12 campl-main-content">
        <div class="campl-content-container">
            <h2>PHP Libraries</h2>
            <p>You can enable or disable the libraries you want.</p>
            <form action="{% url 'sitesmanagement.views.php_libs' service_id=service.id %}" method="post">
                {% if error_message %}<p style="color: red">{{ error_message }}</p>{% endif %}
                <fieldset>
                    {% csrf_token %}
                    <div>
                        {{ form.as_p }}
                    </div>
                    <p><input type="submit" value="Submit" class="campl-btn campl-primary-cta"/></p>
                </fieldset>
            </form>
            {% if not service.primary %}
            <p>PHP Libraries installed in the production server:</p>
                <ul>
                    {% for php_lib in service.site.production_service.php_libs.all %}
                    <li>{{ php_lib.name }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block campl_foot_js %}
    <script>
        $(document).ready(function() {
            $("#id_php_libs").select2();
        });
    </script>
{% endblock %}